# Generated by Django 5.0.6 on 2024-07-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modified_at',
            new_name='modified_date',
        ),
    ]
