# Generated by Django 5.0.6 on 2024-07-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_delete_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'catgories'},
        ),
    ]
